name: LambdaDeploy

on:
  push:
    branches: [ main ]   # run when you push to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Create Lambda zip package
        run: |
          zip -r lambda.zip .

      - name: Upload artifact to S3
        run: |
          aws s3 cp lambda.zip s3://scalable-arch-codedeploy-jyothi/lambda.zip

      - name: Deploy new code to Lambda
        run: |
          aws lambda update-function-code \
            --function-name YOUR_LAMBDA_FUNCTION_NAME_HERE \
            --s3-bucket scalable-arch-codedeploy-jyothi \
            --s3-key lambda.zip \
            --publish
